modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/UncleClapton/StepUp"
license="All rights reversed"

[[mods]]
modId="stepupplus"
version="${version}"
state="Working"
displayName="StepUpPlus"
updateJSONURL="https://github.com/UncleClapton/StepUp/raw/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/stepup"
logoFile="logo.png"
credits="NotTooManyItems, frakier, Emirhangg, Bletch1971, UncleClapton"
authors="UncleClapton"
description='''
3 options allow you to choose between no auto jump, Minecraft auto jump, and StepUp auto jump
'''

[[dependencies.stepup]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"

[[dependencies.stepup]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4,)"
ordering="NONE"
side="CLIENT"
